version: '3.2'
services:
  datashield:
    container_name: datashield_datashield
    build:
      context: .
      dockerfile: Dockerfile.datashield_client
    networks:
    - opal_net
    tty: true
  opal:
    container_name: datashield_opal
    image: opal_docker:latest
    ports:
    - "8843:8443"
    - "8880:8080"
    networks:
    - opal_net
    environment:
    - OPAL_ADMINISTRATOR_PASSWORD=password
    - RSERVER_PORT_6312_TCP_ADDR=datashield_rserver
    - MONGODBHOST=datashield_mongo
    - INITTESTDATA=true
    volumes:
    - ./ds_data/opal:/srv
  rserver:
    container_name: datashield_rserver
    image: obiba/opal-rserver:latest
    ports:
    - "6612:6312"
    - "6611:6311"
    networks:
    - opal_net
  mongo:
    container_name: datashield_mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./ds_data/mongo_data:/data/db
    networks:
    - opal_net
networks:
  opal_net:
