version: '3.2'
services:
  datashield:
    container_name: datashield_datashield
    image: datashield_client
    networks:
    - opal_net
    tty: true
  opal:
    container_name: datashield_opal
    image: obiba/opal:snapshot
    ports:
    - "8843:8443"
    - "8880:8080"
    networks:
    - opal_net
    environment:
    - OPAL_ADMINISTRATOR_PASSWORD=password
    volumes:
    - ./ds_data/opal:/srv
  rserver:
    container_name: datashield_rserver
    image: obiba/opal-rserver:snapshot
    ports:
    - "6612:6312"
    - "6611:6311"
    networks:
    - opal_net
  agate:
    container_name: datashield_agate
    image: obiba/agate:latest
    ports:
    - "8844:8444"
    - "8881:8081"
    networks:
      - opal_net
    volumes:
    - ./ds_data/agate:/srv
  mongo:
    container_name: datashield_mongo
    image: mongo
    volumes:
    - ./ds_data/mongo_data:/data/db
    networks:
    - opal_net
networks:
  opal_net:
