version: '3.5'
services:
  opal:
    container_name: datashield_opal
    image: opal_docker:latest
    ports:
    - "8843:8443"
    - "8880:8080"
    networks:
    - opal_net
    environment:
    - OPAL_ADMINISTRATOR_PASSWORD=${OPAL_ADMIN_PASS}
    - RSERVER_PORT_6312_TCP_ADDR=${R_SERVER_HOST}
    - MONGODBHOST=${OPAL_MONGODB_HOST}
    - INITTESTDATA=true
    volumes:
    - ./ds_data/opal:/srv
  rserver:
    container_name: datashield_rserver
    image: obiba/opal-rserver:latest
    ports:
    - "6612:6312"
    - "6611:6311"
    networks:
    - opal_net
  mongo:
    container_name: datashield_mongo
    image: mongo
    volumes:
    - ./ds_data/mongo_data:/data/db
    networks:
    - opal_net
networks:
  opal_net:
    name: ds_opal_opal_net
